; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -p=instcombine -S | FileCheck %s

;; When instcombine replaces zext->sub with a sext instruction, the debug
;; location of the new instruction should be propagated from the sub
;; instruction.

define fastcc ptr @widget(ptr %arg, i1 %arg1) {
; CHECK-LABEL: define fastcc ptr @widget(
; CHECK-SAME: ptr [[ARG:%.*]], i1 [[ARG1:%.*]]) {
; CHECK-NEXT:  [[BB:.*:]]
; CHECK-NEXT:    [[ZEXT_NEG:%.*]] = sext i1 [[ARG1]] to i32, !dbg [[DBG4:![0-9]+]]
; CHECK-NEXT:    store i32 [[ZEXT_NEG]], ptr [[ARG]], align 4
; CHECK-NEXT:    ret ptr null
;
bb:
  %zext = zext i1 %arg1 to i32
  %sub = sub i32 0, %zext, !dbg !4
  store i32 %sub, ptr %arg, align 4
  ret ptr null
}

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!3}

!0 = distinct !DICompileUnit(language: DW_LANG_C11, file: !1, producer: "clang version 21.0.0git", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, enums: !2, retainedTypes: !2, globals: !2, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "test.c", directory: "/tmp")
!2 = !{}
!3 = !{i32 2, !"Debug Info Version", i32 3}
!4 = !DILocation(line: 2183, column: 45, scope: !5)
!5 = distinct !DISubprogram(name: "widget", scope: !1, file: !1, line: 2134, type: !6, scopeLine: 2146, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition | DISPFlagOptimized, unit: !0, retainedNodes: !2)
!6 = distinct !DISubroutineType(types: !2)
;.
; CHECK: [[META0:![0-9]+]] = distinct !DICompileUnit(language: DW_LANG_C11, file: [[META1:![0-9]+]], producer: "{{.*}}clang version {{.*}}", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, enums: [[META2:![0-9]+]], retainedTypes: [[META2]], globals: [[META2]], splitDebugInlining: false, nameTableKind: None)
; CHECK: [[META1]] = !DIFile(filename: "test.c", directory: {{.*}})
; CHECK: [[META2]] = !{}
; CHECK: [[DBG4]] = !DILocation(line: 2183, column: 45, scope: [[META5:![0-9]+]])
; CHECK: [[META5]] = distinct !DISubprogram(name: "widget", scope: [[META1]], file: [[META1]], line: 2134, type: [[META6:![0-9]+]], scopeLine: 2146, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition | DISPFlagOptimized, unit: [[META0]], retainedNodes: [[META2]])
; CHECK: [[META6]] = distinct !DISubroutineType(types: [[META2]])
;.
